name: Veracode Build DotNet Application
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Build
        run: |
          cd app
          dotnet restore
          dotnet publish -p:UseAppHost=False -p:MapFileExtensions=False -c Release -o ./output
          
      - name: Create zip archive
        run: |
          cd app
          zip -r veracode.zip ./output

      - uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: app/veracode.zip
